### ISSUE TITLE
post-commit hook, help, executable version and auto-push if appropriate

### ISSUE THREAD

**Issue by LrWm3** [kungfusheep/i#1]
I thought this was a pretty cool project. i spend most of my time in the cli so its great for logging things. I have been making some tweaks to it myself on a fork: https://github.com/LrWm3/i

I added a git post-commit hook to log all commits made locally on any github project into 'i'. I found I was typing out my commit messages twice, once for git and once for i. I had trouble figuring out how to find and run 'i.sh' from the post-commit hook though, I ended up hard-coding the path to where I had saved it.

the nice thing about this is it makes it easy to summarize what I did over the week since I don't need to feed in the git history.

I adjusted 'i.sh' to allow for executing from the cli directly if it is run as a script. Sourcing still works. I found that was a bit easier to work with for the post-commit hook.

I added a help which is executed if arguments are `help, -h or --help`, or if nothing else is provided.

I added an 'automatic push' command that runs in the background silently if `origin` is configured as a remote. if no origin remote is configured, nothing is pushed.

cheers!

**Comment by kungfusheep** [comment]
Hey - this is great! 

Everything you added I'd find useful myself, so I'd be happy if you wanted to submit a PR.  

Only thing I noticed was the i source directory was hard coded in the hook definition - is that possible to work around?

Thanks!

**Comment by LrWm3** [comment]
I will look into that and see if I can find a way

**Comment by LrWm3** [comment]
One option i got to work is to have is to have i.sh installed on the users PATH. Then I can check if i.sh is found in the post-commit hook and use it if it is found.

however, this would require updating the installation instructions to include placing `i.sh` on the path.

what do you think about this approach?

edit: will open the PR to make it easier to comment on it.
